a := A_ScriptDir
logs := a "\important\log.txt"    ; set the path to the log file
empty := a "\important\empty.txt"    ; set the path to an empty file
temps := a "\important\temp.txt"
trash := a "\important\trash.txt"    ; set the path to a temporary file
retstat := a "\important\return.txt"    ; set the path to the return status file
files := [logs, empty, temps, trash, retstat]
exe := "`"" a "\lib\AutoHotKey Exe\AutoHotkeyV1.exe`" "     ; specify the path to the AutoHotkey V1 executable
autogui := "`"" a "\important\MacroCreator.ahk`""   ; specify the path to the AutoGUI script
com := exe autogui     ; concatenate the two paths
gif := a "\lib\loadings.gif"    ; specify the path to the gif files